/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/test/java/repository/support/ByNamedQueryUtilIT.p.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package uoc.tfm.emilio.repository.support;

import static org.fest.assertions.Assertions.assertThat;

import javax.inject.Inject;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

import com.jaxio.jpa.querybyexample.*;

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath*:spring/applicationContext-test.xml" })
@Transactional
public class ByNamedQueryUtilIT {

    @Inject
    private ByNamedQueryUtil byNamedQueryUtil;

    @Test
    public void allAccountsUsingNamedQuery() {
        SearchParameters searchParameters = new SearchParameters().namedQuery("User.selectAll");
        assertThat(byNamedQueryUtil.findByNamedQuery(searchParameters)).hasSize(1);
    }

    @Test
    public void allAccountsUsingNativeNamedQuery() {
        SearchParameters searchParameters = new SearchParameters().namedQuery("User.selectAll.native");
        assertThat(byNamedQueryUtil.findByNamedQuery(searchParameters)).hasSize(1);
    }
}