/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/test/java/domain/ModelTest.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package uoc.tfm.emilio.domain;

import static org.fest.assertions.Assertions.assertThat;

import java.io.*;
import java.util.*;

import org.junit.Test;

import uoc.tfm.emilio.util.ValueGenerator;

/**
 * Basic tests for User
 */
@SuppressWarnings("unused")
public class UserTest {

    // test unique primary key
    @Test
    public void newInstanceHasNoPrimaryKey() {
        User model = new User();
        assertThat(model.isIdSet()).isFalse();
    }

    @Test
    public void isIdSetReturnsTrue() {
        User model = new User();
        model.setId(ValueGenerator.getUniqueInteger());
        assertThat(model.getId()).isNotNull();
        assertThat(model.isIdSet()).isTrue();
    }

    @Test
    public void equalsUsingBusinessKey() {
        User model1 = new User();
        User model2 = new User();
        String username = ValueGenerator.getUniqueString(100);
        model1.setUsername(username);
        model2.setUsername(username);
        assertThat(model1).isEqualTo(model2);
        assertThat(model2).isEqualTo(model1);
        assertThat(model1.hashCode()).isEqualTo(model2.hashCode());
    }
}