/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/main/java/printer/Printer.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package uoc.tfm.emilio.printer;

import java.util.Locale;

import javax.inject.Named;
import javax.inject.Singleton;

import uoc.tfm.emilio.domain.User;
import uoc.tfm.emilio.domain.User_;
import uoc.tfm.emilio.printer.support.GenericPrinter;

/**
 * {@link GenericPrinter} for {@link User} 
 *
 * @see GenericPrinter
 * @see TypeAwarePrinter
 */
@Named
@Singleton
public class UserPrinter extends GenericPrinter<User> {
    public UserPrinter() {
        super(User.class, User_.username);
    }

    @Override
    public String print(User user, Locale locale) {
        if (user == null) {
            return "";
        }
        StringBuilder ret = new StringBuilder();
        appendIfNotEmpty(ret, user.getUsername());
        return ret.toString();
    }
}