/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/test/java/service/ModelGenerator.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package uoc.tfm.emilio.repository;

import javax.inject.Named;
import javax.inject.Singleton;

import uoc.tfm.emilio.domain.User;
import uoc.tfm.emilio.util.ValueGenerator;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@Named
@Singleton
public class UserGenerator {

    /**
     * Returns a new User instance filled with random values.
     */
    public User getUser() {
        User user = new User();

        // simple attributes follows
        user.setUsername(ValueGenerator.getUniqueString(100));
        user.setPassword("a");
        user.setIsEnabled(true);
        return user;
    }

}