/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/LazyDataModel.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package uoc.tfm.emilio.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import org.primefaces.model.LazyDataModel;

import uoc.tfm.emilio.domain.User;
import uoc.tfm.emilio.repository.UserRepository;
import uoc.tfm.emilio.web.domain.support.GenericLazyDataModel;
import uoc.tfm.emilio.web.faces.ConversationContextScoped;

/**
 * Provide PrimeFaces {@link LazyDataModel} for {@link User}
 */
@Named
@ConversationContextScoped
public class UserLazyDataModel extends GenericLazyDataModel<User, Integer, UserSearchForm> {
    private static final long serialVersionUID = 1L;

    @Inject
    public UserLazyDataModel(UserRepository userRepository, UserController userController, UserSearchForm userSearchForm, UserExcelExporter userExcelExporter) {
        super(userRepository, userController, userSearchForm, userExcelExporter);
    }
}