/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/EditForm.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package uoc.tfm.emilio.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import uoc.tfm.emilio.domain.User;
import uoc.tfm.emilio.repository.UserRepository;
import uoc.tfm.emilio.web.domain.support.GenericEditForm;
import uoc.tfm.emilio.web.faces.ConversationContextScoped;

/**
 * View Helper/Controller to edit {@link User}.
 */
@Named
@ConversationContextScoped
public class UserEditForm extends GenericEditForm<User, Integer> {
    @Inject
    protected UserController userController;

    @Inject
    public UserEditForm(UserRepository userRepository) {
        super(userRepository);
    }

    /**
     * The entity to edit/view.
     */
    public User getUser() {
        return getEntity();
    }

    public String print() {
        return userController.print(getUser());
    }
}
