/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/ExcelExporter.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package uoc.tfm.emilio.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import uoc.tfm.emilio.domain.User;
import uoc.tfm.emilio.web.domain.support.GenericExcelExporter;
import uoc.tfm.emilio.web.faces.ConversationContextScoped;

/**
 * Exports to excel document {@link User} search criteria and result. 
 */
@Named
@ConversationContextScoped
public class UserExcelExporter extends GenericExcelExporter<User> {
    @Inject
    protected UserSearchForm sf;

    public UserExcelExporter() {
        super("user_username", "user_password", "user_isEnabled");
    }

    @Override
    protected void fillResultItem(int row, User item) {
        int col = 0;
        setValue(row, col++, item.getUsername());
        setValue(row, col++, item.getPassword());
        setValue(row, col++, item.getIsEnabled());
    }

    @Override
    public void fillSearchCriteria(int row) {
        useCriteriaSheet();

        setSelector(row++, 0, "user_username", sf.getUsernameSelector());
        setSelector(row++, 0, "user_password", sf.getPasswordSelector());
        setSelector(row++, 0, "user_isEnabled", sf.getIsEnabledSelector());
    }
}